### ISSUE TITLE
Push latest image to official Lightbend registry

### ISSUE THREAD

**Issue by justinhj** [cloudstateio/samples-ui-shoppingcart#13]
The current image needs to be pushed to `lightbend-docker-registry.bintray.io/cloudstate-samples/frontend`

This can be (probably) done with the following command (in the frontend folder)

`DOCKER_PUBLISH_TO=lightbend-docker-registry.bintray.io/cloudstate-samples npm run dockerbuildpush`

**Comment by vkorenev** [comment]
@justinhj I built a docker image from commit a8eb071735dd06f1366a3764830b5d58865877fa (tagged as [`v0.1.0`](https://github.com/cloudstateio/samples-ui-shoppingcart/releases/tag/v0.1.0) in git) and uploaded it to [`lightbend-docker-registry.bintray.io/cloudstate-samples/frontend`](https://bintray.com/beta/#/lightbend/registry/cloudstate-samples:frontend?tab=overview) with tags `0.1.0` and `latest`.
Also, IMO `package.json` is not a very good place for general scripts. I'd rather delete Docker commands form there and created a separate shell script for building and pushing an image and adding a git tag. What do you think?

**Comment by vkorenev** [comment]
Upd. It seems that a newer image tagged `latest` has been pushed there. I don't know what sources was it build from.
